import Head from "next/head";
import { NextPage } from "next";
import styles from "../styles/index.module.css";
import jwt from "jsonwebtoken";

export async function getStaticProps() {
  const key = process.env.NEXT_PUBLIC_METABASE_SECRET_KEY || "";

  const payload = {
    resource: { dashboard: 3 },
    params: {},
    exp: Math.round(Date.now() / 1000) + 10 * 60, // 10 minute expiration
  };

  const token = jwt.sign(JSON.stringify(payload), key);
  return { props: { token } };
}

const Home: NextPage<{ token: string }> = ({ token }) => {
  return (
    <main>
      <Head>
        <title>Aplicação NextJs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <header className={styles.header}>NextJs Application</header>
      </div>

      <div>
        <iframe
          className={styles.metabase_container}
          src={
            process.env.NEXT_PUBLIC_METABASE_SITE_URL +
            "/embed/dashboard/" +
            token +
            "#theme=transparent&bordered=true&titled=true"
          }
        ></iframe>
      </div>

      <div>
        <footer className={styles.footer}>Footer</footer>
      </div>
    </main>
  );
};

export default Home;
